In [15]:
import pandas as pd
path ="C:/Users/Abdoulie Balisa/Downloads/airline_dataset.csv"
airlines = pd.read_csv(path)
airlines.head(5)

,id,day,airline,destination,dest_region,dest_size,boarding_area,dept_time,wait_min,cleanliness,safety,satisfaction
0,1,Sunday,Airline D,New York,North America,Small,Gate D,3,18,Bad,Safe,Dissatisfied
1,2,Thursday,Airline D,Dubai,North America,Medium,Gate D,2,161,Poor,Moderate,Dissatisfied
2,3,Friday,Airline C,Tokyo,North America,Medium,Gate D,4,136,Bad,Unsafe,Dissatisfied
3,4,Sunday,Airline C,New York,Asia,Small,Gate A,2,158,Excellent,Safe,Dissatisfied
4,5,Wednesday,Airline B,Paris,Middle East,Large,Gate A,14,119,Bad,Safe,Satisfied

In [8]:
categories = {
    "day": {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"},
    "airline": {"Airline A", "Airline B", "Airline C", "Airline D"},
    "destination": {"New York", "London", "Paris", "Tokyo", "Dubai"},
    "dest_region": {"North America", "Europe", "Asia", "Middle East"},
    "dest_size": {"Small", "Medium", "Large"},
    "boarding_area": {"Gate A", "Gate B", "Gate C", "Gate D"},
    "dept_time": set(range(0, 24)),  # Hours (0 to 23)
    "wait_min": set(range(5, 181)),  # Waiting time (5 to 180 minutes)
    "cleanliness": {"Good", "Excellent", "Poor"},  # Valid cleanliness values
    "safety": {"Safe", "Moderate", "Unsafe"},
    "satisfaction": {"Satisfied", "Neutral", "Dissatisfied"},
}

In [10]:
cat_clean = set(airlines['cleanliness']).difference(categories['cleanliness'])
cat_clean

{'Average', 'Bad'}

In [29]:
# Find rows with that category
cat_clean_rows = airlines[airlines['cleanliness'].isin(cat_clean)]
cat_clean_rows.head()

,id,day,airline,destination,dest_region,dest_size,boarding_area,dept_time,wait_min,cleanliness,safety,satisfaction
0,1,Sunday,Airline D,New York,North America,Small,Gate D,3,18,Bad,Safe,Dissatisfied
2,3,Friday,Airline C,Tokyo,North America,Medium,Gate D,4,136,Bad,Unsafe,Dissatisfied
4,5,Wednesday,Airline B,Paris,Middle East,Large,Gate A,14,119,Bad,Safe,Satisfied
9,10,Wednesday,Airline B,Tokyo,Asia,Medium,Gate C,21,14,Bad,Unsafe,Dissatisfied
11,12,Wednesday,Airline B,Dubai,Europe,Small,Gate B,13,175,Average,Moderate,Neutral

In [32]:
valid_clean_rows = airlines[~airlines['cleanliness'].isin(cat_clean)]
valid_clean_rows.head()

,id,day,airline,destination,dest_region,dest_size,boarding_area,dept_time,wait_min,cleanliness,safety,satisfaction
1,2,Thursday,Airline D,Dubai,North America,Medium,Gate D,2,161,Poor,Moderate,Dissatisfied
3,4,Sunday,Airline C,New York,Asia,Small,Gate A,2,158,Excellent,Safe,Dissatisfied
5,6,Friday,Airline D,London,Middle East,Small,Gate C,18,144,Good,Moderate,Satisfied
6,7,Friday,Airline C,Paris,Europe,Medium,Gate D,1,6,Poor,Safe,Dissatisfied
7,8,Sunday,Airline A,Tokyo,Middle East,Small,Gate C,11,149,Poor,Unsafe,Satisfied

In [33]:
print(airlines['dest_region'].unique())
print(airlines['dest_size'].unique())

['North America' 'Asia' 'Middle East' 'Europe']
['Small' 'Medium' 'Large']

In [ ]:
# Replace "Dr." with empty string ""
airlines['full_name'] = airlines['full_name'].str.replace("Dr.","")

# Replace "Mr." with empty string ""
airlines['full_name'] = airlines['full_name'] = airlines['full_name'].str.replace("Mr.","")


# Replace "Miss" with empty string ""
airlines['full_name'] = airlines['full_name'].str.replace("Miss","")


# Replace "Ms." with empty string "
airlines['full_name'] =airlines['full_name'].str.replace("Ms.","")


# Assert that full_name has no honorifics
assert airlines['full_name'].str.contains('Ms.|Mr.|Miss|Dr.').any() == False